### PR TITLE
Dev organizer

### PR DESCRIPTION
**Pull request by HAYATO-Kz**
- Implement Django administration action for organizer can choose room for each topic
- Implement room button to show topic in the room
- add frontend test

### CODE REVIEW

**Comment by TongThanaphon** [comment]
travis fail? I think try add coverage into **requirements.txt**.

**Comment by HAYATO-Kz** [comment]
because  URL that we use in the test is the deployed application we need to merge this to master then I think Travis will work

**Comment by TongThanaphon** [comment]
OK.

**Comment by khaopanbit** [comment]
Got it

**Pull request merged**
