### PR TITLE
Merge dev into master branch

### PR DESCRIPTION
**Pull request by HAYATO-Kz**
add Login feature 
    - Client can login with their Github ID and Google ID

### CODE REVIEW

**Comment by TongThanaphon** [comment]
Is it conflicts?

**Comment by khaopanbit** [comment]
aight worked

**Comment by HAYATO-Kz** [comment]
> Is it conflicts?

Ok,I resolved the conflict.

**Comment by TongThanaphon** [comment]
Very good. Let's merge.

**Pull request closed without merging**
